"""Fixed controls and paths for the RTNS Timerlat campaign."""

from pathlib import Path

from realsense_bench_common.settings import (
    BENCHKIT_PATH,
    CPU_LOCK_SCRIPT,
    CPU_RESTORE_SCRIPT,
    PAPER_CPU_FREQUENCY_MHZ,
    REPO_ROOT,
    TOOLS_DIR,
)


TOOL_DIR = TOOLS_DIR / "realsense_timerlat_bench"
STEADY_TOOL_DIR = TOOLS_DIR / "realsense_steady_bench"
DEFAULT_CONFIG = TOOL_DIR / "configs" / "minimal_matrix.json"
DEFAULT_BUILD_DIR = REPO_ROOT / "build-realsense-timerlat"
DEFAULT_RESULTS_DIR = TOOL_DIR / "results"

CAMPAIGN_CPU_FREQUENCY_MHZ = PAPER_CPU_FREQUENCY_MHZ
CAMPAIGN_CPU_LIST = "0-3"
CAMPAIGN_TIMERLAT_PERIOD_US = 1000
CAMPAIGN_TIMERLAT_POLICY = "f:95"
CAMPAIGN_TIMERLAT_BUCKET_US = 1
CAMPAIGN_TIMERLAT_ENTRIES = 10000
CAMPAIGN_TIMERLAT_WARMUP_SECONDS = 10
CAMPAIGN_TIMERLAT_DURATION_SECONDS = 300
CAMPAIGN_REPETITIONS = 5
CAMPAIGN_CAMERA_POLICY = "SCHED_OTHER"
CAMPAIGN_CAMERA_GUARD_SECONDS = 5
CAMPAIGN_CPU_NOISE_WORKERS = 4
CAMPAIGN_DROP_CACHES_BEFORE_RUN = True

KERNEL_LABELS = ("linux_non_rt", "linux_preempt_rt")
