#!/usr/bin/env python3
"""Benchkit campaign for RealSense steady-state frame acquisition."""

from __future__ import annotations

import argparse
import json
import math
import os
from pathlib import Path
import signal
import sys
from typing import Any, Dict, List

_BOOTSTRAP_TOOL_DIR = Path(__file__).resolve().parent
_BOOTSTRAP_TOOLS_DIR = _BOOTSTRAP_TOOL_DIR.parent
sys.path.insert(0, str(_BOOTSTRAP_TOOLS_DIR))

from steady_settings import (
    BENCHKIT_PATH,
    CAMPAIGN_BACKEND,
    CAMPAIGN_BENCHMARK_CPUS,
    CAMPAIGN_CPU_ISOLATION_ENABLED,
    CAMPAIGN_HOUSEKEEPING_CPUS,
    CPU_NOISE_MODES,
    DEFAULT_BROADCOM_VULKAN_ICD,
    DEFAULT_BUILD_DIR,
    DEFAULT_LIME,
    DEFAULT_MAX_ATTEMPTS_PER_RUN,
    DEFAULT_RECOVER_ON_FAILURE,
    DEFAULT_RECOVERY_RESET_TIMEOUT_MS,
    DEFAULT_RECOVERY_SETTLE_SECONDS,
    DEFAULT_RECOVERY_WAIT_SECONDS,
    DEFAULT_RESET_BEFORE_RUN,
    DEFAULT_RESULTS_DIR,
    FIXED_CAMPAIGN_CONSTANTS,
    GPU_NOISE_MODES,
    MEMORY_NOISE_MODES,
    MODELED_POLICIES,
    NCNN_MODEL_PARAM,
    POLICY_NAMES,
    TOOL_DIR,
    TOOLS_DIR,
    USB_STORAGE_NOISE_MODES,
)

if not BENCHKIT_PATH.exists():
    raise SystemExit("deps/benchkit is missing; initialize repository submodules first.")
sys.path.insert(0, str(BENCHKIT_PATH))
sys.path.insert(0, str(TOOL_DIR))
sys.path.insert(0, str(TOOLS_DIR))

from benchkit.campaign import CampaignCartesianProduct  # noqa: E402
from steady_benchmark import RealSenseSteadyBench  # noqa: E402


def load_cases(path: Path) -> List[Dict[str, Any]]:
    value = json.loads(path.read_text(encoding="utf-8"))
    cases = value.get("cases", []) if isinstance(value, dict) else value
    if not isinstance(cases, list):
        raise ValueError(f"{path} does not contain a case list")
    seen = set()
    for case in cases:
        if not isinstance(case, dict) or not case.get("case_id"):
            raise ValueError(f"Case without case_id: {case!r}")
        if case["case_id"] in seen:
            raise ValueError(f"Duplicate case_id: {case['case_id']}")
        seen.add(case["case_id"])
    return cases


def run_with_cleanup(
    campaign: CampaignCartesianProduct,
    benchmark: RealSenseSteadyBench,
) -> None:
    previous_handlers = {
        signum: signal.getsignal(signum)
        for signum in (signal.SIGHUP, signal.SIGTERM)
    }

    def stop_campaign(signum: int, _frame: Any) -> None:
        raise KeyboardInterrupt(f"received signal {signum}")

    for signum in previous_handlers:
        signal.signal(signum, stop_campaign)
    try:
        campaign.run()
        benchmark.assert_all_runs_successful()
    finally:
        campaign_failed = sys.exc_info()[0] is not None
        try:
            benchmark.cleanup()
        except Exception as error:
            if not campaign_failed:
                raise
            print(f"[CLEANUP] {error}", file=sys.stderr)
        for signum, handler in previous_handlers.items():
            signal.signal(signum, handler)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--config",
        type=Path,
        default=TOOL_DIR / "configs" / "smoke_matrix.json",
    )
    parser.add_argument("--case", dest="case_ids", action="append")
    parser.add_argument("--policies", nargs="+", choices=POLICY_NAMES, default=["other"])
    parser.add_argument(
        "--scheduler-profile",
        "--deadline-profile",
        dest="deadline_profile",
        type=Path,
        help=(
            "per-thread model generated by generate_deadline_profile.py; "
            "required for deadline, rr-rm, and fifo-rm"
        ),
    )
    parser.add_argument("--nb-runs", type=int, default=1)
    parser.add_argument(
        "--frames",
        type=int,
        help=(
            "override measured deliveries and select legacy frame-count mode "
            "unless --measurement-duration-seconds is also supplied"
        ),
    )
    parser.add_argument(
        "--measurement-duration-seconds",
        type=float,
        help=(
            "override every case with a fixed wall-clock measurement duration; "
            "this takes precedence over the legacy frame-count stopping condition"
        ),
    )
    parser.add_argument(
        "--scheduler-apply-after-frames",
        "--deadline-apply-after-frames",
        dest="deadline_apply_after_frames",
        type=int,
        help=(
            "per-camera pre-modeled-scheduler warm-up deliveries; default is "
            "10 percent of warm-up, capped at one second"
        ),
    )
    parser.add_argument(
        "--deadline-allow-partial-profile",
        action="store_true",
        help=(
            "apply SCHED_DEADLINE only to workers listed in the profile and "
            "leave other live workers under SCHED_OTHER"
        ),
    )
    parser.add_argument("--serial", dest="serials", action="append")
    parser.add_argument("--build-dir", type=Path, default=DEFAULT_BUILD_DIR)
    parser.add_argument("--results-dir", type=Path, default=DEFAULT_RESULTS_DIR)
    parser.add_argument("--lime", type=Path, default=DEFAULT_LIME)
    parser.add_argument("--no-lime", action="store_true")
    parser.add_argument(
        "--v4l2-diagnostics",
        action="store_true",
        help="record low-overhead V4L2 select/metadata/DQBUF/callback/requeue stages",
    )
    parser.add_argument(
        "--v4l2-diagnostics-build-only",
        action="store_true",
        help=(
            "compile the V4L2 diagnostic markers to preserve a calibrated "
            "binary layout, but do not record or parse their event stream"
        ),
    )
    parser.add_argument(
        "--overrun-kernel-trace",
        action="store_true",
        help=(
            "record all-CPU IRQ/softirq, V4L2, SIGXCPU, and the exact "
            "6.12.96 Deadline-throttle kprobe"
        ),
    )
    parser.add_argument(
        "--freshness-kernel-trace",
        action="store_true",
        help=(
            "record low-volume UVC/VB2/V4L2 and exceptional xHCI events, "
            "then correlate them with raw librealsense sequence gaps; "
            "implies --v4l2-diagnostics"
        ),
    )
    parser.add_argument("--no-sudo", action="store_true")
    parser.add_argument(
        "--backend",
        choices=("v4l2", "rsusb"),
        default=CAMPAIGN_BACKEND,
        help=(
            "librealsense USB backend; paper campaigns default to v4l2, "
            "while rsusb is reserved for separate backend validation"
        ),
    )
    parser.add_argument(
        "--rsusb-usb-device",
        dest="rsusb_usb_devices",
        action="append",
        default=[],
        metavar="USB_DEVICE",
        help=(
            "USB composite sysfs name to unbind from uvcvideo for RSUSB, "
            "for example 3-1; repeat for every connected test camera"
        ),
    )
    parser.add_argument(
        "--cpu-isolation",
        action=argparse.BooleanOptionalAction,
        default=CAMPAIGN_CPU_ISOLATION_ENABLED,
        help=(
            "place the campaign in an isolated cgroup-v2 CPU partition and "
            "pin automatically discovered RealSense xHCI IRQs to the "
            "housekeeping CPUs (default: enabled)"
        ),
    )
    parser.add_argument(
        "--housekeeping-cpus",
        default=CAMPAIGN_HOUSEKEEPING_CPUS,
        help="Linux CPU list reserved for housekeeping and camera xHCI IRQs",
    )
    parser.add_argument(
        "--benchmark-cpus",
        default=CAMPAIGN_BENCHMARK_CPUS,
        help="Linux CPU list for the benchmark, librealsense, and noise",
    )
    parser.add_argument(
        "--recover-on-failure",
        choices=("none", "full-reset"),
        default=DEFAULT_RECOVER_ON_FAILURE,
        help=(
            "Recover failed camera startup before continuing (default: full-reset). "
            "A full reset covers every selected RealSense composite USB device."
        ),
    )
    parser.add_argument(
        "--reset-before-run",
        action=argparse.BooleanOptionalAction,
        default=DEFAULT_RESET_BEFORE_RUN,
        help=(
            "full-reset every selected camera before attempt 1 of each logical "
            "run so repetitions do not inherit pipeline state (default: enabled)"
        ),
    )
    parser.add_argument(
        "--recovery-reset-timeout-ms",
        type=int,
        default=DEFAULT_RECOVERY_RESET_TIMEOUT_MS,
        help=(
            "Per-camera RealSense firmware reset timeout "
            f"(default: {DEFAULT_RECOVERY_RESET_TIMEOUT_MS} ms)"
        ),
    )
    parser.add_argument(
        "--recovery-wait-seconds",
        type=float,
        default=DEFAULT_RECOVERY_WAIT_SECONDS,
        help=(
            "Per-camera USB re-enumeration timeout "
            f"(default: {DEFAULT_RECOVERY_WAIT_SECONDS:g} s)"
        ),
    )
    parser.add_argument(
        "--recovery-settle-seconds",
        type=float,
        default=DEFAULT_RECOVERY_SETTLE_SECONDS,
        help=(
            "Delay after resetting all cameras and before retry "
            f"(default: {DEFAULT_RECOVERY_SETTLE_SECONDS:g} s)"
        ),
    )
    parser.add_argument(
        "--max-attempts-per-run",
        type=int,
        default=DEFAULT_MAX_ATTEMPTS_PER_RUN,
        help=(
            "Maximum startup attempts for one logical Benchkit run "
            f"(default: {DEFAULT_MAX_ATTEMPTS_PER_RUN})"
        ),
    )
    parser.add_argument(
        "--cpu-noise-modes",
        nargs="+",
        choices=CPU_NOISE_MODES,
        default=["none"],
        help="Cartesian CPU-noise variable; busy_loop uses register-only arithmetic",
    )
    parser.add_argument(
        "--cpu-noise-workers",
        type=int,
        default=max(1, os.cpu_count() or 1),
        help="busy-loop worker count; defaults to the number of logical CPUs",
    )
    parser.add_argument("--cpu-noise-warmup-seconds", type=float, default=10.0)
    parser.add_argument("--cpu-noise-ready-timeout-seconds", type=float, default=30.0)
    parser.add_argument(
        "--cpu-noise-cpu-affinity",
        help="optional taskset CPU list inherited by every busy-loop worker",
    )
    parser.add_argument(
        "--memory-noise-modes",
        nargs="+",
        choices=MEMORY_NOISE_MODES,
        default=["none"],
        help="Cartesian memory-noise variable; fixed_copy streams between private buffers",
    )
    parser.add_argument(
        "--memory-noise-workers",
        type=int,
        default=max(1, os.cpu_count() or 1),
        help="fixed-copy worker count; defaults to the number of logical CPUs",
    )
    parser.add_argument(
        "--memory-noise-buffer-size-mib",
        type=int,
        default=64,
        help="size of each source and destination buffer per worker (default: 64 MiB)",
    )
    parser.add_argument(
        "--memory-noise-target-mib-per-second",
        type=float,
        default=0.0,
        help=(
            "aggregate estimated read+write traffic limit for fixed_copy; "
            "0 preserves unlimited traffic"
        ),
    )
    parser.add_argument(
        "--memory-noise-copy-chunk-kib",
        type=int,
        default=1024,
        help=(
            "copy and pacing quantum within each fixed_copy buffer "
            "(default: 1024 KiB)"
        ),
    )
    parser.add_argument("--memory-noise-warmup-seconds", type=float, default=10.0)
    parser.add_argument(
        "--memory-noise-ready-timeout-seconds", type=float, default=30.0
    )
    parser.add_argument(
        "--memory-noise-cpu-affinity",
        help="optional taskset CPU list inherited by every fixed-copy worker",
    )
    parser.add_argument(
        "--gpu-noise-modes",
        nargs="+",
        choices=GPU_NOISE_MODES,
        default=["none"],
        help="Cartesian GPU-noise variable; the only workload is pinned MobileNetV2+ncnn Vulkan",
    )
    parser.add_argument("--gpu-noise-device", type=int, default=0)
    parser.add_argument("--gpu-noise-warmup-iterations", type=int, default=10)
    parser.add_argument("--gpu-noise-ready-timeout-seconds", type=float, default=60.0)
    parser.add_argument("--gpu-noise-cpu-affinity")
    parser.add_argument(
        "--usb-storage-noise-modes",
        nargs="+",
        choices=USB_STORAGE_NOISE_MODES,
        default=["none"],
        help="Cartesian USB storage noise variable; only read-only sequential I/O is supported",
    )
    parser.add_argument(
        "--usb-storage-device",
        type=Path,
        help="unmounted whole USB disk, preferably a stable /dev/disk/by-id path",
    )
    parser.add_argument("--usb-storage-warmup-seconds", type=float, default=10.0)
    parser.add_argument("--usb-storage-block-size-kib", type=int, default=1024)
    parser.add_argument(
        "--usb-storage-ready-timeout-seconds", type=float, default=30.0
    )
    parser.add_argument(
        "--gpu-noise-vulkan-icd",
        type=Path,
        help="Vulkan ICD JSON; auto-selects the Raspberry Pi Broadcom ICD when present",
    )
    parser.add_argument(
        "--build-jobs",
        type=int,
        default=max(1, (os.cpu_count() or 2) - 1),
        help="Parallel build jobs; defaults to leaving one CPU free",
    )
    args = parser.parse_args()
    if args.build_jobs < 1:
        raise SystemExit("--build-jobs must be positive")
    if args.backend == "rsusb" and not args.rsusb_usb_devices:
        raise SystemExit(
            "--backend rsusb requires at least one --rsusb-usb-device"
        )
    if args.backend == "v4l2" and args.rsusb_usb_devices:
        raise SystemExit(
            "--rsusb-usb-device is only valid with --backend rsusb"
        )
    if args.recovery_reset_timeout_ms < 1:
        raise SystemExit("--recovery-reset-timeout-ms must be positive")
    if args.recovery_wait_seconds <= 0:
        raise SystemExit("--recovery-wait-seconds must be positive")
    if args.recovery_settle_seconds < 0:
        raise SystemExit("--recovery-settle-seconds must be non-negative")
    if args.max_attempts_per_run < 1:
        raise SystemExit("--max-attempts-per-run must be positive")
    if (
        args.measurement_duration_seconds is not None
        and args.measurement_duration_seconds <= 0
    ):
        raise SystemExit("--measurement-duration-seconds must be positive")
    if (
        args.deadline_apply_after_frames is not None
        and args.deadline_apply_after_frames < 1
    ):
        raise SystemExit("--deadline-apply-after-frames must be positive")
    if args.max_attempts_per_run > 1 and args.recover_on_failure == "none":
        raise SystemExit("multiple attempts require --recover-on-failure")
    if args.cpu_noise_workers < 1:
        raise SystemExit("--cpu-noise-workers must be positive")
    if args.cpu_noise_warmup_seconds <= 0:
        raise SystemExit("--cpu-noise-warmup-seconds must be positive")
    if args.cpu_noise_ready_timeout_seconds <= args.cpu_noise_warmup_seconds:
        raise SystemExit(
            "--cpu-noise-ready-timeout-seconds must exceed the warm-up duration"
        )
    if args.memory_noise_workers < 1:
        raise SystemExit("--memory-noise-workers must be positive")
    if args.memory_noise_buffer_size_mib < 1:
        raise SystemExit("--memory-noise-buffer-size-mib must be positive")
    if args.memory_noise_copy_chunk_kib < 1:
        raise SystemExit("--memory-noise-copy-chunk-kib must be positive")
    memory_noise_buffer_size_kib = args.memory_noise_buffer_size_mib * 1024
    if args.memory_noise_copy_chunk_kib > memory_noise_buffer_size_kib:
        raise SystemExit(
            "--memory-noise-copy-chunk-kib must not exceed the buffer size"
        )
    if memory_noise_buffer_size_kib % args.memory_noise_copy_chunk_kib != 0:
        raise SystemExit(
            "--memory-noise-copy-chunk-kib must divide the buffer size exactly"
        )
    if (
        not math.isfinite(args.memory_noise_target_mib_per_second)
        or args.memory_noise_target_mib_per_second < 0.0
    ):
        raise SystemExit(
            "--memory-noise-target-mib-per-second must be finite and non-negative"
        )
    if (
        args.memory_noise_target_mib_per_second > 0.0
        and args.memory_noise_target_mib_per_second < 1.0
    ):
        raise SystemExit(
            "--memory-noise-target-mib-per-second must be zero or at least 1"
        )
    if args.memory_noise_warmup_seconds <= 0:
        raise SystemExit("--memory-noise-warmup-seconds must be positive")
    if args.memory_noise_ready_timeout_seconds <= args.memory_noise_warmup_seconds:
        raise SystemExit(
            "--memory-noise-ready-timeout-seconds must exceed the warm-up duration"
        )
    if args.gpu_noise_warmup_iterations < 1:
        raise SystemExit("--gpu-noise-warmup-iterations must be positive")
    if args.gpu_noise_ready_timeout_seconds <= 0:
        raise SystemExit("--gpu-noise-ready-timeout-seconds must be positive")
    if args.usb_storage_warmup_seconds <= 0:
        raise SystemExit("--usb-storage-warmup-seconds must be positive")
    if args.usb_storage_block_size_kib < 4:
        raise SystemExit("--usb-storage-block-size-kib must be at least 4")
    if args.usb_storage_ready_timeout_seconds <= args.usb_storage_warmup_seconds:
        raise SystemExit(
            "--usb-storage-ready-timeout-seconds must exceed the warm-up duration"
        )
    if (
        any(mode != "none" for mode in args.usb_storage_noise_modes)
        and args.usb_storage_device is None
    ):
        raise SystemExit(
            "--usb-storage-device is required for sequential-read USB noise"
        )
    if (
        args.gpu_noise_vulkan_icd is None
        and DEFAULT_BROADCOM_VULKAN_ICD.is_file()
        and any(mode != "none" for mode in args.gpu_noise_modes)
    ):
        args.gpu_noise_vulkan_icd = DEFAULT_BROADCOM_VULKAN_ICD
    if any(mode != "none" for mode in args.gpu_noise_modes):
        ncnn_root = NCNN_MODEL_PARAM.parents[2]
        missing = [
            path
            for path in (ncnn_root / "CMakeLists.txt", NCNN_MODEL_PARAM)
            if not path.is_file()
        ]
        if missing:
            detail = ", ".join(str(path) for path in missing)
            raise SystemExit(
                "GPU noise requires the pinned ncnn submodule and MobileNetV2 "
                f"model; missing: {detail}. Run: git submodule update --init "
                "--recursive deps/ncnn"
            )

    cases = load_cases(args.config)
    if args.case_ids:
        wanted = set(args.case_ids)
        cases = [case for case in cases if case["case_id"] in wanted]
        missing = wanted - {case["case_id"] for case in cases}
        if missing:
            raise SystemExit("Unknown case_id(s): " + ", ".join(sorted(missing)))
    if args.frames is not None:
        for case in cases:
            probe = case.setdefault("probe", {})
            probe["frames"] = args.frames
            if args.measurement_duration_seconds is None:
                probe.pop("measurement_duration_ms", None)
    if args.measurement_duration_seconds is not None:
        duration_ms = round(args.measurement_duration_seconds * 1000)
        for case in cases:
            probe = case.setdefault("probe", {})
            probe["measurement_duration_ms"] = duration_ms
            probe.pop("measurement_timeout_ms", None)
    if args.deadline_apply_after_frames is not None:
        for case in cases:
            case.setdefault("probe", {})["deadline_apply_after_frames"] = (
                args.deadline_apply_after_frames
            )
    if args.deadline_allow_partial_profile:
        for case in cases:
            case.setdefault("probe", {})["deadline_allow_partial_profile"] = True
    if args.serials:
        for case in cases:
            case.setdefault("probe", {})["serials"] = args.serials
            case["probe"]["camera_count"] = len(args.serials)
            case.setdefault("physical", {})["camera_count"] = len(args.serials)
    if args.backend == "rsusb":
        for case in cases:
            probe = case.setdefault("probe", {})
            camera_count = int(
                probe.get(
                    "camera_count",
                    case.get("physical", {}).get("camera_count", 1),
                )
            )
            if len(args.rsusb_usb_devices) != camera_count:
                raise SystemExit(
                    "RSUSB requires one --rsusb-usb-device per selected camera; "
                    f"case {case['case_id']!r} selects {camera_count} camera(s) "
                    f"but provides {len(args.rsusb_usb_devices)} USB device(s)"
                )
            probe["rsusb_usb_devices"] = list(args.rsusb_usb_devices)
    if not cases:
        raise SystemExit("No cases selected")
    if args.deadline_profile is not None:
        if len(cases) != 1:
            raise SystemExit(
                "--scheduler-profile can override exactly one selected case; "
                "use per-case probe.deadline_profile values for a multi-case matrix"
            )
        deadline_profile = args.deadline_profile.resolve()
        if not deadline_profile.is_file():
            raise SystemExit(
                f"Scheduler model profile does not exist: {deadline_profile}"
            )
        for case in cases:
            case.setdefault("probe", {})["deadline_profile"] = str(deadline_profile)
    modeled_policies = MODELED_POLICIES.intersection(args.policies)
    if modeled_policies:
        missing_profiles = [
            str(case["case_id"])
            for case in cases
            if not case.get("probe", {}).get("deadline_profile")
        ]
        if missing_profiles:
            raise SystemExit(
                "modeled scheduling requires --scheduler-profile (or its "
                "--deadline-profile compatibility alias) or a per-case "
                "probe.deadline_profile; missing for: " + ", ".join(missing_profiles)
            )
        for case in cases:
            profile = Path(case["probe"]["deadline_profile"]).resolve()
            if not profile.is_file():
                raise SystemExit(
                    f"Scheduler profile for case {case['case_id']!r} does not exist: "
                    f"{profile}"
                )
            case["probe"]["deadline_profile"] = str(profile)
    if args.recover_on_failure == "full-reset" or args.reset_before_run:
        for case in cases:
            probe = case.get("probe", {})
            serials = probe.get("serials", probe.get("serial", []))
            if isinstance(serials, str):
                serials = [serials] if serials else []
            camera_count = int(
                probe.get(
                    "camera_count",
                    case.get("physical", {}).get("camera_count", 1),
                )
            )
            if len(serials) != camera_count:
                raise SystemExit(
                    "full-reset recovery requires one explicit --serial per "
                    f"selected camera; case {case['case_id']!r} selects "
                    f"{camera_count} camera(s) but provides {len(serials)} serial(s)"
                )

    args.results_dir.mkdir(parents=True, exist_ok=True)
    benchmark = RealSenseSteadyBench(
        cases=cases,
        build_dir=args.build_dir,
        lime=args.lime,
        use_lime=not args.no_lime,
        v4l2_diagnostics=(
            args.v4l2_diagnostics or args.freshness_kernel_trace
        ),
        overrun_kernel_trace=args.overrun_kernel_trace,
        freshness_kernel_trace=args.freshness_kernel_trace,
        use_sudo=not args.no_sudo,
        backend=args.backend,
        rsusb_usb_devices=tuple(args.rsusb_usb_devices),
        cpu_isolation_enabled=args.cpu_isolation,
        housekeeping_cpus=args.housekeeping_cpus,
        benchmark_cpus=args.benchmark_cpus,
        cpu_noise_modes=args.cpu_noise_modes,
        cpu_noise_workers=args.cpu_noise_workers,
        cpu_noise_warmup_seconds=args.cpu_noise_warmup_seconds,
        cpu_noise_ready_timeout_seconds=args.cpu_noise_ready_timeout_seconds,
        cpu_noise_cpu_affinity=args.cpu_noise_cpu_affinity,
        memory_noise_modes=args.memory_noise_modes,
        memory_noise_workers=args.memory_noise_workers,
        memory_noise_buffer_size_mib=args.memory_noise_buffer_size_mib,
        memory_noise_copy_chunk_kib=args.memory_noise_copy_chunk_kib,
        memory_noise_target_mib_per_second=(
            args.memory_noise_target_mib_per_second
        ),
        memory_noise_warmup_seconds=args.memory_noise_warmup_seconds,
        memory_noise_ready_timeout_seconds=args.memory_noise_ready_timeout_seconds,
        memory_noise_cpu_affinity=args.memory_noise_cpu_affinity,
        gpu_noise_modes=args.gpu_noise_modes,
        gpu_noise_device=args.gpu_noise_device,
        gpu_noise_warmup_iterations=args.gpu_noise_warmup_iterations,
        gpu_noise_ready_timeout_seconds=args.gpu_noise_ready_timeout_seconds,
        gpu_noise_cpu_affinity=args.gpu_noise_cpu_affinity,
        gpu_noise_vulkan_icd=args.gpu_noise_vulkan_icd,
        usb_storage_noise_modes=args.usb_storage_noise_modes,
        usb_storage_device=args.usb_storage_device,
        usb_storage_warmup_seconds=args.usb_storage_warmup_seconds,
        usb_storage_block_size_kib=args.usb_storage_block_size_kib,
        usb_storage_ready_timeout_seconds=args.usb_storage_ready_timeout_seconds,
        recover_on_failure=args.recover_on_failure,
        reset_before_run=args.reset_before_run,
        recovery_reset_timeout_ms=args.recovery_reset_timeout_ms,
        recovery_wait_seconds=args.recovery_wait_seconds,
        recovery_settle_seconds=args.recovery_settle_seconds,
        max_attempts_per_run=args.max_attempts_per_run,
        build_jobs=args.build_jobs,
        v4l2_diagnostics_build_only=args.v4l2_diagnostics_build_only,
    )
    campaign_constants = {
        **FIXED_CAMPAIGN_CONSTANTS,
        "fixed_librealsense_backend": args.backend,
        "fixed_usb_kernel_driver": (
            "uvcvideo" if args.backend == "v4l2" else "none"
        ),
        "fixed_cpu_isolation": args.cpu_isolation,
        "fixed_housekeeping_cpus": (
            args.housekeeping_cpus if args.cpu_isolation else ""
        ),
        "fixed_benchmark_cpus": (
            args.benchmark_cpus if args.cpu_isolation else ""
        ),
    }
    campaign = CampaignCartesianProduct(
        name="realsense_steady",
        benchmark=benchmark,
        nb_runs=args.nb_runs,
        variables={
            "case_id": [case["case_id"] for case in cases],
            "policy": args.policies,
            "cpu_noise": args.cpu_noise_modes,
            "memory_noise": args.memory_noise_modes,
            "gpu_noise": args.gpu_noise_modes,
            "usb_storage_noise": args.usb_storage_noise_modes,
        },
        constants=campaign_constants,
        debug=False,
        gdb=False,
        enable_data_dir=True,
        continuing=False,
        benchmark_duration_seconds=None,
        results_dir=str(args.results_dir),
    )
    run_with_cleanup(campaign, benchmark)


if __name__ == "__main__":
    main()
