#!/usr/bin/env python3
"""Generate the native-TikZ P1 host-latency figure."""

from __future__ import annotations

import argparse
import csv
from collections import defaultdict
from pathlib import Path


ROOT = Path(__file__).resolve().parent
DATA = ROOT / "derived"
OUTPUT = ROOT / "figures/main-matrix-host-latency-tikz.tex"

POLICIES = ("OTHER", "RR-RM", "FIFO-RM", "Deadline")
NOISES = ("None", "CPU", "Memory", "GPU")
KERNELS = (("standard", "non-RT"), ("rt", r"PREEMPT\_RT"))
WORKLOADS = ("30 FPS", "60 FPS")
COLORS = {
    "OTHER": "pOneOther",
    "RR-RM": "pOneRr",
    "FIFO-RM": "pOneFifo",
    "Deadline": "pOneDeadline",
}


def read_rows(name: str) -> list[dict[str, str]]:
    with (DATA / name).open(newline="", encoding="utf-8") as source:
        return list(csv.DictReader(source))


def fmt(value: float) -> str:
    return f"{value:.4f}".rstrip("0").rstrip(".")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--metric", choices=("p99", "max"), default="p99")
    parser.add_argument("--output", type=Path)
    args = parser.parse_args()
    metric_key = f"{args.metric}_ms"
    output = args.output or (
        OUTPUT if args.metric == "p99"
        else ROOT / "figures/main-matrix-host-latency-max-tikz.tex"
    )
    axis_label = "p99 host latency (ms)" if args.metric == "p99" else "Max host latency (ms)"
    summary_rows = read_rows("main_matrix_host_latency_summary.csv")
    run_rows = read_rows("main_matrix_host_latency_runs.csv")
    summary = {
        (row["kernel"], row["workload"], row["noise"], row["policy"]): row
        for row in summary_rows
    }
    runs: dict[tuple[str, str, str, str], list[float]] = defaultdict(list)
    for row in run_rows:
        runs[
            (row["kernel"], row["workload"], row["noise"], row["policy"])
        ].append(float(row[metric_key]))
    if len(summary) != 64 or any(len(values) != 3 for values in runs.values()):
        raise ValueError("Expected 64 cells with three latency runs per cell")
    if args.metric == "max":
        for key, points in runs.items():
            if max(points) != float(summary[key][metric_key]):
                raise ValueError(f"Maximum does not match the per-run values: {key}")

    lines = [
        "% Generated by scripts/figures/generate_main_matrix_host_latency_tikz.py.",
        r"\begin{tikzpicture}[x=1cm,y=1cm,font=\scriptsize]",
        r"  \definecolor{pOneOther}{HTML}{666666}",
        r"  \definecolor{pOneRr}{HTML}{0072B2}",
        r"  \definecolor{pOneFifo}{HTML}{E69F00}",
        r"  \definecolor{pOneDeadline}{HTML}{009E73}",
        r"  \definecolor{pOneNonFresh}{HTML}{B2182B}",
    ]

    legend_x = 1.42
    for index, policy in enumerate(POLICIES):
        x = legend_x + index * 2.10
        lines.extend(
            [
                rf"  \fill[{COLORS[policy]}] ({fmt(x)},8.54) rectangle ++(0.34,0.18);",
                rf"  \node[anchor=west] at ({fmt(x + 0.43)},8.63) {{{policy}}};",
            ]
        )
    lines.extend(
        [
            r"  \fill[black] (9.86,8.63) circle (0.035);",
            r"  \node[anchor=west] at (9.90,8.63) {single run};",
            r"  \node[text=pOneNonFresh,anchor=west] at (11.45,8.63) {NF};",
            r"  \node[anchor=west] at (11.93,8.63) {non-fresh count};",
            r"  \draw[dashed,line width=0.45pt] (14.28,8.63)--(14.78,8.63);",
            r"  \node[anchor=west] at (14.78,8.63) {frame period};",
        ]
    )

    panel_width = 7.20
    panel_height = 3.55
    panel_gap = 0.65
    panel_lefts = (0.85, 0.85 + panel_width + panel_gap)
    panel_bottoms = (4.65, 0.9125)
    plot_left_offset = 0.75
    plot_right_offset = 0.15
    plot_bottom_offset = 0.48
    plot_top_offset = 0.42
    group_step = 1.43
    group_start = 1.20
    policy_offsets = (-0.405, -0.135, 0.135, 0.405)
    bar_width = 0.245

    for workload_index, workload in enumerate(WORKLOADS):
        if workload == "30 FPS":
            y_min, y_max = 32.0, 37.0
            ticks = (32, 33, 34, 35, 36, 37)
            nominal = 1000.0 / 30.0
        else:
            y_min, y_max = 12.0, 38.0
            ticks = (12, 16, 20, 24, 28, 32, 36)
            nominal = 1000.0 / 60.0
        if args.metric == "max":
            y_min, y_max = 0.0, 120.0 if workload == "30 FPS" else 80.0
            ticks = tuple(range(0, int(y_max) + 1, 20))
        for kernel_index, (kernel, kernel_label) in enumerate(KERNELS):
            panel_left = panel_lefts[kernel_index]
            panel_bottom = panel_bottoms[workload_index]
            plot_left = panel_left + plot_left_offset
            plot_right = panel_left + panel_width - plot_right_offset
            plot_bottom = panel_bottom + plot_bottom_offset
            plot_top = panel_bottom + panel_height - plot_top_offset
            plot_height = plot_top - plot_bottom

            def y_position(value: float) -> float:
                clipped = min(y_max, max(y_min, value))
                return plot_bottom + (clipped - y_min) * plot_height / (y_max - y_min)

            lines.append(
                rf"  \node[font=\small\bfseries] at ({fmt((plot_left + plot_right) / 2)},{fmt(panel_bottom + panel_height - 0.07)}) {{{kernel_label}, {workload}}};"
            )
            for tick in ticks:
                y = y_position(float(tick))
                lines.extend(
                    [
                        rf"  \draw[gray!45,dashed,line width=0.35pt] ({fmt(plot_left)},{fmt(y)})--({fmt(plot_right)},{fmt(y)});",
                        rf"  \node[anchor=east,font=\tiny] at ({fmt(plot_left - 0.10)},{fmt(y)}) {{{tick}}};",
                    ]
                )
            nominal_y = y_position(nominal)
            lines.append(
                rf"  \draw[black!80,dashed,line width=0.55pt] ({fmt(plot_left)},{fmt(nominal_y)})--({fmt(plot_right)},{fmt(nominal_y)});"
            )
            lines.extend(
                [
                    rf"  \draw[line width=0.45pt] ({fmt(plot_left)},{fmt(plot_bottom)})--({fmt(plot_right)},{fmt(plot_bottom)});",
                    rf"  \draw[line width=0.45pt] ({fmt(plot_left)},{fmt(plot_bottom)})--({fmt(plot_left)},{fmt(plot_top)});",
                ]
            )

            for noise_index, noise in enumerate(NOISES):
                group_x = plot_left + group_start + noise_index * group_step
                if workload_index == 1:
                    lines.append(
                        rf"  \node[anchor=north,font=\scriptsize] at ({fmt(group_x)},{fmt(plot_bottom - 0.08)}) {{{noise}}};"
                    )
                for policy_index, policy in enumerate(POLICIES):
                    key = (kernel, workload, noise, policy)
                    row = summary[key]
                    x = group_x + policy_offsets[policy_index]
                    top = y_position(float(row[metric_key]))
                    lines.append(
                        rf"  \fill[{COLORS[policy]}] ({fmt(x - bar_width / 2)},{fmt(plot_bottom)}) rectangle ({fmt(x + bar_width / 2)},{fmt(top)});"
                    )
                    points = runs[key]
                    for dot_offset, point in zip((-0.055, 0.0, 0.055), points):
                        lines.append(
                            rf"  \fill[black] ({fmt(x + dot_offset)},{fmt(y_position(point))}) circle (0.026);"
                        )
                    non_fresh = int(row["problem_framesets"])
                    if non_fresh:
                        label_y = min(
                            plot_top - 0.05,
                            max(y_position(point) for point in points) + 0.15,
                        )
                        lines.append(
                            rf"  \node[text=pOneNonFresh,font=\scriptsize,fill=white,inner sep=0.25pt,anchor=south] at ({fmt(x)},{fmt(label_y)}) {{{non_fresh}}};"
                        )

            if kernel_index == 0:
                center_y = (plot_bottom + plot_top) / 2
                lines.append(
                    rf"  \node[rotate=90,font=\scriptsize] at ({fmt(panel_left + 0.03)},{fmt(center_y)}) {{{axis_label}}};"
                )

    lines.extend(
        [
            r"  \node[font=\small] at (8.38,0.725) {Interference};",
            r"\end{tikzpicture}",
            "",
        ]
    )
    output.write_text("\n".join(lines), encoding="utf-8")


if __name__ == "__main__":
    main()
